project_id = "uzimddhgsfkjzdzexpjr"

[functions.create-delivery-person]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
